name: SexGuard
version: 1.5.1
main: sex\guard\Manager
api: 5.0.0
authors:
  - sex_KAMAZ
  - seetch
load: POSTWORLD

commands:
  rg:
    description: 'Shows help or a list of region management commands'
    permission: 'sexguard.command.rg'

permissions:
  sexguard.command.rg:
    default: true
  sexguard.noflag:
    description: 'Ignoring flags within regions'
    default: op
  sexguard.all:
    description: 'Access to all SexGuard functions'
    default: op