name: SexGuard
version: 1.4.4
main: sex\guard\Manager
api: 4.0.0
authors:
  - sex_KAMAZ
  - seetch
load: POSTWORLD

commands:
  rg:
    description: 'Показывает помощь или список команд управления регионами'
    permission: 'sexguard.command.rg'

permissions:
  sexguard.command.rg:
    default: true
  sexguard.noflag:
    description: 'Игнорирование флагов внутри регионов'
    default: op
  sexguard.all:
    description: 'Доступ ко всем функциям sexGuard'
    default: op