name: SexGuard
main: sex\guard\Manager
version: 1.3.3
api: 4.0.0

author: sex_KAMAZ
website: https://vk.com/infernopage

load: POSTWORLD

commands:
  rg:
    description: 'Показывает помощь или список команд управления регионами'
    permission: 'sexguard.command.rg'

permissions:
  sexguard.command.rg:
    default: true
  sexguard.noflag:
    description: 'Игнорирование флагов внутри регионов'
    default: op
  sexguard.all:
    description: 'Доступ ко всем функциям sexGuard'
    default: op