---
# Configuration version, don't edit this.
config-version: 1.4.1

language: ru

# The support of the Permission Manager plugin allows you to determine the size and number of regions for each (or separate) of its groups.
# Otherwise, the default element in group.yml will be used for all players.
# You can setup groups in groups.yml.
pureperms-support: false
universalgroup-support: false
sexgroup-support: false

# The support of the Economy plugin allows you to work with the economy to be able to sell regions.
economyapi-support: false
universalmoney-support: false
econ-support: false

# The visual selection of the region when selecting by default
show-selection: true

# Allow owners to sell their regions through a sign. Relevant for creating hotels.
# Sign format:
# 1 line: sell region
# 2 line: price
region-sell: false

# Set a mandatory fee for players without full access for creating a new region with the help of a team.
region-create-paid: false
# The price of creating a region (if the parameter is higher than true).
region-create-price: 100

# Prohibits players without full access to put and break blocks while they are outside the region with the flag allowed for that, or outside their region.
safe-mode: false

# In this mode, each new region will be created without taking into account the height (like a chunk).
# I don't know why anyone needs this feature, but creating regions with it is really convenient.
# Please note that in the size settings regions instead of their volume in blocks will be the area is calculated (excluding height).
full-height: false

# A way to notify players when actions within regions are banned.
# Popup - 0, Message - 1, Tip - 2.
notification-type: 2

# Standard flag values when creating a new region.
# interact: opening the yellow doors, pressing buttons, etc.
# teleport: teleportation from the region.
# combust:  igniting creatures.
# explode:  any explosions inside the region.
# change:   changing the region by creatures (falling sand, etc.).
# bucket:   using buckets.
# damage:   taking damage from the outside world.
# chest:    access to chests.
# frame:    access to the frames.
# place:    the ability to place blocks.
# break:    the ability to break blocks.
# sleep:    the ability to go to bed.
# decay:    allow foliage to disappear from trees.
# drop:     the ability to throw things away.
# chat:     sending messages to the chat.
# pvp:      the ability to deal damage to players.
# mob:      ability to damage creatures.
default-flags:
  interact: true
  teleport: true
  combust: false
  explode: false
  change: false
  bucket: false
  damage: true
  chest: false
  frame: false
  place: false
  break: false
  sleep: false
  decay: true
  drop: true
  chat: true
  pvp: false
  mob: true

# Flags that can be reassigned in the game via /rg flag.
# To prevent players from changing any flag, simply delete or comment it out.
# But only after you create service regions (spawn, arena, etc.)
allowed-flags:
  - interact
  - teleport
  - combust
  - explode
  - change
  - bucket
  - damage
  - chest
  - frame
  - place
  - break
  - sleep
  - decay
  - drop
  - chat
  - pvp
  - mob
...